### ISSUE TITLE
Restart server, impossible to get out of a vehicle

### ISSUE THREAD

**Issue by HalCroves** [lilfuchs/esx_drp_garage#10]
Hello, 
I'm really glad you took this script !

But i have a "little" problem.
I leave the car, I put it away (the is stored), I disconnect, I restart the server.

When I restart the server (cache empty or not) and I try to get out a car stored, I have as a message "Your car has been impounded!" (your car is not in the garage).

In data base the "state" of the car is well at 1or 0 (owned_vehicles).

To be able to take cars out of the garage, I have to restart the script manually :/

=> actually i have add a cron for restart the script.

Do you have an idea ?

Thanks on advance.

**Comment by OhTanoshi** [comment]
Sorry for not replying quickly. but i recently left esx since i went to a full custom game mode. that being said im note sure what the issues could be sicne it was working for me before the switch. but ill take a look when i have time

**Comment by HalCroves** [comment]
Hello, No problem.

I found a workaround for the script to work. I perform a cron on my dedicated every 30 minutes. This allows the script to "load correctly".

I am looking a lot and start to understand a little more the operation of fivem scripts.

For the moment, I have no real trouble with your script, since there is a workaround :)

Thanks for your replies.

**Comment by OhTanoshi** [comment]
@HalCroves i reverted changes. on the [stable branch](https://github.com/lilfuchs/esx_drp_garage/tree/stable) this will make everything work correctly if you havent changed from my garage system.
