### ISSUE TITLE
Only one of my players has problem with car menu - can't confirm the selection

### ISSUE THREAD

**Issue by MoravianLion** [lilfuchs/esx_drp_garage#11]
Hi,

one of my player (and I have a lot of them, but this is only case that occurs) goes to the garage to take out the vehicle from his DB and he sees the selection of his cars, but upon confirming that, nothing happens. Car won't spawn. Only this error has been found in his client, but honestly, I have no idea how should I fix this. Could someone take a look at this, please? 

Thank you for your time!

`[    262562] Error running call reference function for resource esx_drp_garage: citizen:/scripting/lua/scheduler.lua:403: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    262562] stack traceback:
[    262562] 	[C]: in function 'error'
[    262562] 	citizen:/scripting/lua/MessagePack.lua:862: in field 'unpack'
[    262562] 	citizen:/scripting/lua/scheduler.lua:626: in field 'Open'
[    262562] 	client.lua:148: in upvalue 'ref'
[    262562] 	citizen:/scripting/lua/scheduler.lua:389: in function <citizen:/scripting/lua/scheduler.lua:388>
[    262562] 	[C]: in function 'xpcall'
[    262562] 	citizen:/scripting/lua/scheduler.lua:388: in function <citizen:/scripting/lua/scheduler.lua:387>
[    262562] stack traceback:
[    262562] 	[C]: in function 'error'
[    262562] 	citizen:/scripting/lua/scheduler.lua:403: in function <citizen:/scripting/lua/scheduler.lua:372>
[    262562] Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
[    262562] stack traceback:
[    262562] 	[C]: in function 'error'
[    262562] 	citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
[    262562] 	citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
[    262562] 	citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
[    262562] 	citizen:/scripting/lua/scheduler.lua:626: in field '?'
[    262562] 	client/functions.lua:1304: in upvalue 'handler'
[    262562] 	citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
[    262562] stack traceback:
[    262562] 	[C]: in function 'error'
[    262562] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[    262562] 	citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
[    263328] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    263531] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    263687] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    263906] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    264094] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    264437] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    264594] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    264781] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    264953] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    265156] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    265375] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    265625] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    266109] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    266484] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    267578] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    267766] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    267953] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    268141] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    268344] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    268531] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    268719] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    268922] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    269094] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    269281] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    269469] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    269672] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    269859] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    270062] error during NUI callback menu_change: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    270687] error during NUI callback menu_submit: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    272297] error during NUI callback menu_submit: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    277578] error during NUI callback menu_submit: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    277750] error during NUI callback menu_submit: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    277953] error during NUI callback menu_submit: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    278109] error during NUI callback menu_submit: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    278281] error during NUI callback menu_submit: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    278547] error during NUI callback menu_submit: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    278797] error during NUI callback menu_submit: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    278969] error during NUI callback menu_submit: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    279187] error during NUI callback menu_submit: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    279422] error during NUI callback menu_submit: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    279609] error during NUI callback menu_submit: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    279812] error during NUI callback menu_submit: citizen:/scripting/lua/MessagePack.lua:862: extra bytes
[    280109] error during NUI callback menu_cancel: citizen:/scripting/lua/MessagePack.lua:862: extra bytes`

**Comment by OhTanoshi** [comment]
Should be fixed.
