### ISSUE TITLE
Cars not Saving

### ISSUE THREAD

**Issue by XxTopKillerzZ** [lilfuchs/esx_drp_garage#2]
Hi,

When i buy a car, its doesnt save in the database and i cant spawn it in the garage
Whats the problem?

Tanks,
TK

**Comment by XxTopKillerzZ** [comment]
Ok, cars are saving now but i have a question
How do i delete the impound thing?

**Comment by BakeryBoss** [comment]
how you sort out problem with saving cars?

**Comment by lilfuchs** [comment]
The impounds cant be removed at the moment. ill look into adding a config or make them optional when i have time. but this was recently replaced  by a new garage im using. which i may be posting soon and will be replacing this.

**Comment by BakeryBoss** [comment]
I sorted as well, if you remove impound from script you will have issue with spawning cars from garage, people would be able to take off from garage same car over and over.

**Comment by lilfuchs** [comment]
@XxTopKillerzZ This should be fixed now?
