### ISSUE TITLE
Addon Car Names in Garage

### ISSUE THREAD

**Issue by Mariox6** [lilfuchs/esx_drp_garage#22]
Hello,

I need help with the addon car names in the garage.
Now it shows the spawn name of the car and i want the normal name.
As example: It shows: rmodmustang and i want Ford Mustang GT.
![Need Help](https://user-images.githubusercontent.com/48855611/55170581-17935380-5177-11e9-9fff-49023dfab778.PNG)

**Comment by OhTanoshi** [comment]
I cant quite remimber how to do this but its been explained a few times on the fivem forums
