### ISSUE TITLE
Issues With MySQL

### ISSUE THREAD

**Issue by AmosesYT** [lilfuchs/esx_drp_garage#33]
[ERROR] [MySQL] An error happens on MySQL for query "UPDATE owned_vehicles SET state =@state WHERE plate=@plate {@state=False}": Unknown column 'plate' in 'where clause'
STATE UPDATED...
09WAN992
[ERROR] [MySQL] An error happens on MySQL for query "UPDATE owned_vehicles SET vehicle=@vehprop WHERE plate=@plate {@vehprop={"modSeats":-1,"neonEnabled":[false,false,false,false],"modStruts":-1,"dirtLevel":0.0079835616052151,"modSteeringWheel":-1,"modEngineBlock":-1,"modXenon":false,"modBrakes":-1,"modEngine":-1,"extras":{"11":false,"10":false},"modHorns":-1,"modShifterLeavers":-1,"modTank":-1,"modHydrolic":-1,"modSideSkirt":-1,"modWindows":-1,"modArchCover":-1,"plate":"09WAN992","modArmor":-1,"modAPlate":-1,"modBackWheels":-1,"modSmokeEnabled":1,"modAirFilter":-1,"modPlateHolder":-1,"modLivery":-1,"modDashboard":-1,"modTransmission":-1,"modRightFender":-1,"modAerials":-1,"tyreSmokeColor":[255,255,255],"color1":29,"modFrontBumper":-1,"plateIndex":0,"modVanityPlate":-1,"wheels":5,"modGrille":-1,"modOrnaments":-1,"pearlescentColor":28,"modSuspension":-1,"windowTint":-1,"modTrunk":-1,"modTurbo":false,"health":1000,"modRoof":-1,"neonColor":[255,0,255],"color2":34,"modDial":-1,"modRearBumper":-1,"modSpeakers":-1,"modExhaust":-1,"modTrimB":-1,"modSpoilers":-1,"modTrimA":-1,"modHood":-1,"model":-1809822327,"modFrontWheels":-1,"modDoorSpeaker":-1,"wheelColor":156,"modFender":-1,"modFrame":-1};@plate=09WAN992}": Unknown column 'plate' in 'where clause'

**Comment by OhTanoshi** [comment]
looks like you could possibly be using a really old esx. or they updated esx and broke compatiablity. maybe someone else using this can comment weather it works still or not.

Should soon be having a c# standalone garage script coming out that will work with esx
