### ISSUE TITLE
cant take a vehicle out of impound

### ISSUE THREAD

**Issue by cedrickalegroso** [lilfuchs/esx_drp_garage#60]
Hi im havign a issue i can take my vehicle out of impound it says 
SCRIPT ERRPR: @esx_drp_garage/server/server.lua:124: attempt to comapre number with nil

**Comment by ThatGuyJacobee** [comment]
I'm getting this too :(

**Comment by cedrickalegroso** [comment]
i fixed mine. @ThatGuyJacobee  are you using it with the latest es_Esxtended?

**Comment by cedrickalegroso** [comment]
@ThatGuyJacobee  check this if you having the same error and with the same line with me this should be the fix it was using old syntax for es so i just changed it to xPlayer.getMoney()
`

    ESX.RegisterServerCallback('eden_garage:checkMoney', function(source, cb)
    local xPlayer = ESX.GetPlayerFromId(source)

    if xPlayer.getMoney() >= Config.Price then
        cb(true)
    else
        cb(false)
    end
    end)
`

**Comment by ThatGuyJacobee** [comment]
Thanks, it worked ❤️
