### ISSUE TITLE
Custom Car names

### ISSUE THREAD

**Issue by Ultrunz** [lilfuchs/esx_drp_garage#8]
![image](https://user-images.githubusercontent.com/13288425/44016963-1107a0b2-9f01-11e8-9fdf-72bca770ef8c.png)
Theyre just NULL

any fixes? :)

**Comment by Ultrunz** [comment]
I've tried a few things and they only make it worse. I just have a few custom cars in the game and this is somewhat game breaking for our server because players don't know what they're taking out

**Comment by Ultrunz** [comment]
I fixed this, Had to make a client.lua run to add custom names

`Citizen.CreateThread(function()
  AddTextEntry("0x3177AF2F", "Dodge Charger Rampage")

end)`

I left just one car in so you can see how I did it. I used to hex generator from OpenIV to get all the hex codes :)

**Comment by lilfuchs** [comment]
Ill have to look into this i know back 5 months ago cars always showed up with the vehicles model name. but alot has changed since then.

**Comment by HunterJones1999** [comment]
Do we have an update? Custom Cars still show up as NULL

**Comment by OhTanoshi** [comment]
I ditched esx a few months ago and stoped all development on fivem so i havent gotten a fix. as far as i know it started going null due to esx updates

**Comment by HunterJones1999** [comment]
Thats, a shame,

Well thank you for this script anyways, I'll Work on it!

**Comment by Ultrunz** [comment]
I gave you a fix for it just scroll up dude

**Comment by HunterJones1999** [comment]
> I gave you a fix for it just scroll up dude

Yeah, I was just hoping there was a main fix so I didnt have to do this for all my cars, I got quite a bit lol I guess its the price I gotta pay :)

**Comment by Ultrunz** [comment]
Yea. I limited the amount of cars I had for that reason lol. It doesnt take too long though. Just use the Hash generator in OpenIV :)

**Comment by HunterJones1999** [comment]
> Yea. I limited the amount of cars I had for that reason lol. It doesnt take too long though. Just use the Hash generator in OpenIV :)

I dont really wanna be a bother, but is it possible you can show me how you did it in the client.lua? I really rather no mess somthing up lol

**Comment by Ultrunz** [comment]
i already did :P

but here is the full one i use

```
Citizen.CreateThread(function()
  AddTextEntry("0xF440915E", "Go Kart")
  AddTextEntry("0x3177AF2F", "Dodge Charger Rampage")
  AddTextEntry("0xFA5D55E9", "Aprilla 450sm")
  AddTextEntry("0x096C8452", "Honda MSX Grom")
  AddTextEntry("0x9E40BD45", "Honda 450 CRF")
  AddTextEntry("0x34C675D5", "Dodge Challenger Demon")
  AddTextEntry("0x72639D6E", "Ferrari La Ferrari")
  AddTextEntry("0xDAA8BED1", "1965 Shelby GT Cobra 427")
  AddTextEntry("0x53675378", "Lamborghini Gallardo")
  AddTextEntry("0x709BE572", "McLaren 12C")
  AddTextEntry("0x8CE3F828", "Lamborghini Hurrican")
  AddTextEntry("0xE441D883", "Audi S8")
  AddTextEntry("0x9BEBF36A", "Cheverolet Corvette Singray")
  AddTextEntry("0xB7D9F7F1", "Declasse Drift Tampa")
  AddTextEntry("0x8539FE02", "Dodge Charger RT")
  AddTextEntry("0xAEA82CCF", "Mercedes Benz s63")
  AddTextEntry("0x684B478A", "VW Camper")
  AddTextEntry("0x8B9C4F03", "250cc Go Kart")
  AddTextEntry("0x38E073D7", "Forgiato Widebody Hellcat Charger")
  AddTextEntry("0x7ABE4872", "2014 Maserati Alfieri Concept Car")
  AddTextEntry("0xE6224504", "2019 McLaren Senna")
  AddTextEntry("0x253955B7", "2017 Ford Raptor")
  AddTextEntry("0xE7B2AD35", "Lamorghini Aventador")
  AddTextEntry("0x7E39B694", "Nissan Skyline")
  AddTextEntry("0x38E073D7", "Nissan Skyline")
  AddTextEntry("0xB4EA749B", "2019 Chiron Divo")
  AddTextEntry("0xED576550", "H1 Hummer")
  AddTextEntry("0x1282EDBE", "Ford Velociraptor")

end)
```

**Comment by eprimex** [comment]
> i already did :P
> 
> but here is the full one i use
> 
> ```
> Citizen.CreateThread(function()
>   AddTextEntry("0xF440915E", "Go Kart")
>   AddTextEntry("0x3177AF2F", "Dodge Charger Rampage")
>   AddTextEntry("0xFA5D55E9", "Aprilla 450sm")
>   AddTextEntry("0x096C8452", "Honda MSX Grom")
>   AddTextEntry("0x9E40BD45", "Honda 450 CRF")
>   AddTextEntry("0x34C675D5", "Dodge Challenger Demon")
>   AddTextEntry("0x72639D6E", "Ferrari La Ferrari")
>   AddTextEntry("0xDAA8BED1", "1965 Shelby GT Cobra 427")
>   AddTextEntry("0x53675378", "Lamborghini Gallardo")
>   AddTextEntry("0x709BE572", "McLaren 12C")
>   AddTextEntry("0x8CE3F828", "Lamborghini Hurrican")
>   AddTextEntry("0xE441D883", "Audi S8")
>   AddTextEntry("0x9BEBF36A", "Cheverolet Corvette Singray")
>   AddTextEntry("0xB7D9F7F1", "Declasse Drift Tampa")
>   AddTextEntry("0x8539FE02", "Dodge Charger RT")
>   AddTextEntry("0xAEA82CCF", "Mercedes Benz s63")
>   AddTextEntry("0x684B478A", "VW Camper")
>   AddTextEntry("0x8B9C4F03", "250cc Go Kart")
>   AddTextEntry("0x38E073D7", "Forgiato Widebody Hellcat Charger")
>   AddTextEntry("0x7ABE4872", "2014 Maserati Alfieri Concept Car")
>   AddTextEntry("0xE6224504", "2019 McLaren Senna")
>   AddTextEntry("0x253955B7", "2017 Ford Raptor")
>   AddTextEntry("0xE7B2AD35", "Lamorghini Aventador")
>   AddTextEntry("0x7E39B694", "Nissan Skyline")
>   AddTextEntry("0x38E073D7", "Nissan Skyline")
>   AddTextEntry("0xB4EA749B", "2019 Chiron Divo")
>   AddTextEntry("0xED576550", "H1 Hummer")
>   AddTextEntry("0x1282EDBE", "Ford Velociraptor")
> 
> end)
> ```

didn't find any more resource hungry way to do it?

**Comment by twistedcinema** [comment]
Im probs a bit late but I downloaded this today and fixed the model name issue.

Make the Vehicle listings tab look like this


-- View Vehicle Listings
function ListVehiclesMenu()
    local elements = {}

    ESX.TriggerServerCallback('eden_garage:getVehicles', function(vehicles)

        for _,v in pairs(vehicles) do

            local hashVehicule = v.vehicle.model
            local vehicleName = GetDisplayNameFromVehicleModel(hashVehicule)
            local labelvehicle
            if(v.state)then
            labelvehicle = vehicleName _U('status_in_garage', GetLabelText(vehicleName))
            
            else
            labelvehicle = vehicleName _U('status_impounded', GetLabelText(vehicleName))
            end    
            table.insert(elements, {label =labelvehicle , value = v})
            
        end

and for the impound section make it look like this.

function ReturnVehicleMenu()

	ESX.TriggerServerCallback('eden_garage:getOutVehicles', function(vehicles)

		local elements = {}

		for _,v in pairs(vehicles) do

			local hashVehicule = v.model
    		local vehicleName = GetDisplayNameFromVehicleModel(hashVehicule)
    		local labelvehicle

    		labelvehicle = vehicleName _U('impound_list', GetLabelText(vehicleName))
    	
			table.insert(elements, {label =labelvehicle , value = v})
			
		end

**Comment by XeroDay99** [comment]
What is the number before the car name?
