### ISSUE TITLE
This vehicle is not yours!

### ISSUE THREAD

**Issue by ariesu98** [lilfuchs/esx_drp_garage#9]
Hi, i have problem with ur script.

I am buying a car, I am going to put it in the garage and I write that the car is not mine.
I tried with add-on and standard cars from the game.
He writes that the car is not mine.
and in the console I have something like this:https://imgur.com/a/U70wRjd

Thanks for help!

**Comment by Ultrunz** [comment]
You need to run esx migrate. the cars are all using the old license plate system on yours. you need to make it the new one

**Comment by afikpr123** [comment]
I Have a same Problem
